In [ ]:
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
def cv2_imshow(img):
    if img.ndim > 2:
        #img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        plt.imshow(img)
    else:
        plt.imshow(img, cmap="gray")
    plt.show()

In [ ]:
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [ ]:
training_size = 50000
testing_size = 10000

In [ ]:
training_dataset = unpickle('images/cifar-100-python/train')
testing_dataset = unpickle('images/cifar-100-python/test')

In [ ]:
training_images = training_dataset[b'data']
training_labels = training_dataset[b'fine_labels']
testing_images = testing_dataset[b'data']
testing_labels = testing_dataset[b'fine_labels']

In [ ]:
training_images = training_images[:training_size]
training_labels = training_labels[:training_size]
testing_images = testing_images[:testing_size]
testing_labels = testing_labels[:testing_size]

In [ ]:
training_images = training_images.reshape(len(training_images),3,32,32).transpose(0,2,3,1)
training_labels = np.array(training_labels)
training_labels = training_labels.reshape(len(training_images), 1)

testing_images = testing_images.reshape(len(testing_images),3,32,32).transpose(0,2,3,1)
testing_labels = np.array(testing_labels)
testing_labels = testing_labels.reshape(len(testing_images), 1)

In [ ]:
print(training_images.shape)
print(training_labels.shape)
print(testing_images.shape)
print(testing_labels.shape)

(50000, 32, 32, 3)
(50000, 1)
(10000, 32, 32, 3)
(10000, 1)


In [ ]:
h = []
h_test = []

In [ ]:
hog = cv2.HOGDescriptor((32,32), (16,16), (8,8), (8,8),9)

In [ ]:
for x in training_images:
    h.append(hog.compute(x))

for x in testing_images:
    h_test.append(hog.compute(x))

print("hog computed")

hog computed


In [ ]:
h = np.array(h)
h_test = np.array(h_test)
print(h.shape)
print(h_test.shape)


(50000, 324)
(10000, 324)


In [ ]:
x_train = h
y_train = training_labels

x_test = h_test
y_test = testing_labels

In [ ]:
y_train=y_train.reshape(-1,)
y_test=y_test.reshape(-1,)

In [ ]:
svclassifier = SVC(kernel='rbf', random_state = 0)
svclassifier.fit(x_train, y_train)

SVC(random_state=0)

In [ ]:
y_pred = svclassifier.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm) 

[[60  1  0 ...  1  1  2]
 [ 0 37  0 ...  0  0  1]
 [ 1  1  6 ...  2  3  1]
 ...
 [ 0  1  1 ... 19  2  0]
 [ 0  0  3 ...  0 15  2]
 [ 0  0  0 ...  0  0 37]]


In [ ]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.67      0.60      0.63       100
           1       0.31      0.37      0.34       100
           2       0.15      0.06      0.09       100
           3       0.14      0.08      0.10       100
           4       0.23      0.17      0.20       100
           5       0.40      0.40      0.40       100
           6       0.14      0.23      0.17       100
           7       0.24      0.22      0.23       100
           8       0.42      0.49      0.45       100
           9       0.60      0.62      0.61       100
          10       0.32      0.38      0.35       100
          11       0.26      0.12      0.16       100
          12       0.30      0.34      0.32       100
          13       0.27      0.29      0.28       100
          14       0.22      0.31      0.26       100
          15       0.27      0.24      0.25       100
          16       0.56      0.40      0.47       100
          17       0.30    